apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: queue-master-weaveworksdemos-queue-master-0-3-1-system-owner-discovery
  namespace: sock-shop
spec:
  action: Block
  message: System owner discovery command execution denied
  process:
    matchPaths:
    - path: /usr/bin/who
    - path: /usr/bin/w
    - path: /usr/bin/id
    - path: /usr/bin/whoami
  selector:
    matchLabels:
      name: queue-master
  severity: 3
  tags:
  - MITRE
  - MITRE_T1082_system_information_discovery
