apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: front-end-weaveworksdemos-front-end-0-3-12-write-in-shm-dir
  namespace: sock-shop
spec:
  action: Block
  file:
    matchDirectories:
    - dir: /dev/shm/
      readOnly: true
      recursive: true
  message: Alert! write to /dev/shm folder prevented.
  selector:
    matchLabels:
      name: front-end
  severity: 5
  tags:
  - MITRE_execution
  - MITRE
