apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: front-end-weaveworksdemos-front-end-0-3-12-write-under-dev-dir
  namespace: sock-shop
spec:
  action: Audit
  file:
    matchDirectories:
    - dir: /dev/
      readOnly: true
      recursive: true
  message: Alert! File creation under /dev/ directory detected.
  selector:
    matchLabels:
      name: front-end
  severity: 5
  tags:
  - NIST
  - NIST_800-53_AU-2
  - NIST_800-53_SI-4
  - MITRE
  - MITRE_T1036_masquerading
