apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: user-weaveworksdemos-user-0-4-7-cis-commandline-warning-banner
  namespace: sock-shop
spec:
  action: Block
  file:
    matchPaths:
    - path: /etc/motd
      readOnly: true
    - path: /etc/issue
      readOnly: true
    - path: /etc/issue.net
      readOnly: true
  message: Alert! write to warning banner file for standard command line login detected
  selector:
    matchLabels:
      name: user
  severity: 5
  tags:
  - CIS
  - CIS_Linux
  - CIS_1.7_Warning_Banners
  - CIS_1.7.1_Command_Line_Warning_Banners
