apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: user-db-weaveworksdemos-user-db-0-4-0-system-owner-discovery
  namespace: sock-shop
spec:
  action: Block
  message: System owner discovery command execution denied
  process:
    matchPaths:
    - path: /usr/bin/who
    - path: /usr/bin/w
    - path: /usr/bin/id
    - path: /usr/bin/whoami
  selector:
    matchLabels:
      name: user-db
  severity: 3
  tags:
  - MITRE
  - MITRE_T1082_system_information_discovery
