apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: catalogue-weaveworksdemos-catalogue-0-3-5-maint-tools-access
  namespace: sock-shop
spec:
  action: Audit
  message: restricted maintenance tool access attempt detected
  process:
    matchDirectories:
    - dir: /sbin/
      recursive: true
  selector:
    matchLabels:
      name: catalogue
  severity: 1
  tags:
  - PCI_DSS
  - MITRE
