apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: payment-weaveworksdemos-payment-0-4-3-write-in-shm-dir
  namespace: sock-shop
spec:
  action: Block
  file:
    matchDirectories:
    - dir: /dev/shm/
      readOnly: true
      recursive: true
  message: Alert! write to /dev/shm folder prevented.
  selector:
    matchLabels:
      name: payment
  severity: 5
  tags:
  - MITRE_execution
  - MITRE
