apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: orders-weaveworksdemos-orders-0-4-7-trusted-cert-mod
  namespace: sock-shop
spec:
  action: Block
  file:
    matchDirectories:
    - dir: /etc/ssl/
      readOnly: true
      recursive: true
    - dir: /etc/pki/
      readOnly: true
      recursive: true
    - dir: /usr/local/share/ca-certificates/
      readOnly: true
      recursive: true
  message: Credentials modification denied
  selector:
    matchLabels:
      name: orders
  severity: 1
  tags:
  - MITRE
  - MITRE_T1552_unsecured_credentials
